### ISSUE TITLE
Fleet-Wide DNS Refactor

### ISSUE THREAD

**Issue by the-maldridge** [voidlinux/void-infrastructure#10]
RFC: Fleet wide DNS refactor
============================

This issue has come up recently that our DNS is not operating as an
optimal system.  This has led to in the past year alone:

  * No builds for a period of approxomately 4 days during a build server cutover.
  * After the cutover, no IPv6 access to repo for a period of 3 days.
  * An ongoing issue with forum.voidlinux.eu and no valid DKIM keys.
  * An excessively long cutover and resolution from repo3 disk exhaustion.

I propose that in light of these events, the DNS of all Void
owned/managed resources should be refactored into a uniform system.
Features of this system will include:

  * DNS that gives an indication of where a server is physically located.
    * The current repoN.voidlinux.<eu,us,org,net,com,de> system does
      not give you any indication if you are pulling from down the
      street or across an ocean.
    * It is not obvious to the infrastructure team where a mirror's
      expected traffic should originate from, this makes GeoIP of
      questionable value.
  * Mirrors are currently for the most part colocated with builders.
    This often means that a build process refers to an artifact
    location via the mirror's DNS.  The new DNS system will not have
    this flaw.
    *  Splitting   mirrors  from  builders  is   already  unecessarily
      complicated, this doesn't help.
    *  In the future with a new build controller, it may be desireable
       to not require build machines to have DNS entries for the build
       to succeed.
  * The DNS system will not have a single point of failure that is a
    person.
    * It has become painfully clear how requiring changes to go
      through a single developer can be slow and lead to months long
      outages.  For this reason and this reason alone, the new DNS
      system will be cloud based under the existing Void Linux GCP
      account (this account also hosts the Chromium translation keys,
      and a few other things related to making Void packages work with
      selected Google products).
    * DNS does not need to be altered often, but when it does it often
      needs to be altered fast.  Google's Cloud DNS has appropriate
      systems in place so that multiple trusted Void maintainers can
      alter DNS when necessary.  Additionally it is being evaluated to
      have a "break glass" functionality to change the DNS from a
      bastion host.
  * A single source of truth.
    * Through the generocity of many different developers, the Void
      project resources can be reached via domains in the .org, .com,
      .net, .us, .eu, .de, and .fr TLDs.  This support is fantastic,
      but it unfortunately means that there are many disjoint DNS
      entries that do not all point to the correct location.
    * All Void resources will be canonically visible via the
      voidlinux.com domain.  This domain has the most wide
      propogation, the .com nameservers have the most widely available
      failover, and the .com TLD is widely recognized and accepted.

To solve these issues and improve the quality of service delivered to
users of Void, the DNS of the entire fleet will be refactored as
follows:

  * repo.voidlinux.com will be a static CNAME which will return the
    complete list of available repos currently in the serving state.
    Over time repo.voidlinux.com will become a CNAME to
    mirrors.voidlinux.com and eventually be phased out.
  * dynrepo.voidlinux.com will utilize GeoIP to attempt to return the
    address of a nearby mirror, it should be stated that DNS is not
    load balancing and this is a necessarily imperfect system.
  * Continent level CNAMEs beneath mirrors.voidlinux.com will be the
    preferred way to access mirrors as far as general users are
    concerned:
    * These configuration files will be provided via configuration
      packages and will replace the currently embedded files in
      /usr/share/xbps.
    * The CNAMEs will be easily identifiable for the locations they
      serve, currently the following CNAMEs would be provisioned:
      * us.mirrors.voidlinux.com
      * eu.mirrors.voidlinux.com
      * apan.mirrors.voidlinux.com (proposed)
      * au.voidlinux.com (proposed)
  * Within each continent level CNAME will be metro-local CNAMEs named
    with respect to the nearest airport using the conventional IATA
    naming scheme.  For example, a mirror located in the Dallas, Texas
    metro would be behind a CNAME of dfw.us.mirrors.voidlinux.com and
    a mirror in San Jose would be behind sjc.us.mirrors.voidlinux.com.
  * The A and AAAA records for a particular mirror would be of the
    form of simple letters below the metro-local CNAME.  To complete
    the example this means that should our friends at UT Dallas wish
    to put their mirror into the DNS pool, it would be accessible as
    a.dfw.us.mirrors.voidlinux.com.
  * Infrastructure hosts such as what is currently build.voidlinux.eu would sit behind build.voidlinux.* and would be identified as buildmaster, buildslave-dfw, buildslave-muc, and so on.  The currently nameless host which handles the monitoring for void will be made available as monitoring.infra.voidlinux.*

---

FAQ:
----

### Why is this worth doing?

This change will allow us to make a unified source of truth for
mirrors and Void resources.  See the issues listed above for why its
important to have a single source of truth.

### What about the old DNS names?

The old names will continue to be served for at least a year.  This
will enable a seamless cutover while the new names are propogated out
and allowed to take over via the normal system update process.

After a period of 1 year the nginx traffic will be reviewed to the
official mirrors to see what names they are being referred to as and
if the requests for the legacy domain name are not present then the
corresponding entry will be dropped.

### Why are you switching to .com from .eu?

.eu is a fine domain, but for a variety of technical reasons, the .com
domain suites the goals outlined here better.

For operators of other domains it is currently being evaluated if an export of the zonefile can be automatically generated to keep all voidlinux domains synchronized.

### What about the website and the forum and the wiki?

The website, forum, and wiki will continue to have the existing names
pointed and will also get new names pointed to them.  They will go
through the same age-out process to use the new names, with the
exception of the forum which will cutover as soon as its new name is
available with a proper DKIM key (this is why people haven't gotten
the registration emails from the forum).

### Will this also mean that I can download everything via SSL?

No, the move to have SSL on all mirrors is a seperate project and will
be completed independently of this project.

### What about the mirror addresses for Tor?

Mirror access via specialized transit will be evaluated seperately.
Currently the Tor endpoint points to a mirror where we have a limited
amount of throughput.  This may require the Tor endpoint to be served
from a different mirror in the future.  This change will be made with
minimal disruption if it becomes necessary.

### I don't like this and I want to complain to someone, but because the DNS is broken I can't get a forum account!

Uhh, you do see what you just agreed with there right?  Anyway if you
really want to complain, you can reach out on IRC.  Updates that are
sufficiently important will be posted into this Issue.

**Comment by chneukirchen** [comment]
+1 for the general idea, but I'd strongly prefer to use a `.org` for the central domain (compare with other distros: Debian, Gentoo, Arch, Fedora).

Pinging @logenkain to see if a domain transfer would be possible.

**Comment by the-maldridge** [comment]
I would also prefer voidlinux.org.  This was written up based on the available information at the time.

**Comment by Vaelatern** [comment]
What else will be under `infra.voidlinux.com`?

**Comment by Ypnose** [comment]
<code>voidlinux.fr</code> will expire in 7 days. I won't renew it. We can try a transfer if you want it.

**Comment by the-maldridge** [comment]
Thanks for the heads up, I'll defer to @Gottox if we want to attempt a transfer.  I believe at this time though we're harmonizing under voidlinux.org with approximately the config discussed above.  I'm closing this issue as its technically resolved, but discussion about the domains that may be expiring soon can still happen here.
