### ISSUE TITLE
{armv6l,armv7l,x86_64}-musl builders 

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-infrastructure#11]
Since ~16th Oct the musl builders no longer have an accurate view of what packages exist in the repo. This breaks the step that determines which packages to build and results in useless rebuilds and not retrying failed builds.

https://build.voidlinux.eu/builders/x86_64-musl_builder/builds/6091/steps/shell_2/logs/stdio
```
[...]
pkgname: libpipeline repover: ? srcpkgver: 1.5.0_1
pkgname: tracker-miners repover: ? srcpkgver: 2.0.3_1
pkgname: python3-yarl repover: ? srcpkgver: 0.14.2_1
pkgname: python-pytest repover: ? srcpkgver: 3.2.4_1
pkgname: faketime repover: ? srcpkgver: 0.9.7_1
pkgname: clerk repover: ? srcpkgver: 4.0.5_1
pkgname: tslib repover: ? srcpkgver: 1.14_1
pkgname: xfce4-whiskermenu-plugin repover: ? srcpkgver: 1.7.4_1
pkgname: neovim-remote repover: ? srcpkgver: 1.8.9_1
pkgname: kwayland-integration repover: ? srcpkgver: 5.11.3_2
[...]
```

Looks like versions are compared to an empty repo. Maybe some path needs to be adjusted after 06077b1803372c2e1090e6692a59edecdad392a8?

**Comment by the-maldridge** [comment]
This issue has been tracked down to the date the builders were moved to a new host.  Here's what we know so far:

  *  The builders are tracked in ansible, so the build configuration is identical
  * The build state directories, chroots, and hostdir were rsync'd across from the old host (limitation of buildbot)
  * The xbps-checkvers output is correct when run outside of xbps-bulk.

This leaves open the following possibilities:
  * bug in xbps-bulk
  * untracked change in the environment
  * particularly bad luck within the infrastructure team

**Comment by Duncaen** [comment]
```
[duncaen@void-repo 1]$ cat /etc/xbps.d/99-repository-local.conf
repository=/hostdir/binpkgs
[duncaen@void-repo 1]$ sudo -u buildbot /sbin/xbps-checkvers --distdir=../void-packages srcpkgs/libpipeline/template srcpkgs/tracker-miners/template srcpkgs/python3-yarl/template srcpkgs/python-pytest/template srcpkgs/faketime/template srcpkgs/clerk/template srcpkgs/tslib/template srcpkgs/xfce4-whiskermenu-plugin/template srcpkgs/neovim-remote/template srcpkgs/kwayland-integration/template
pkgname: gogs repover: 0.9.113_6 srcpkgver: 0.11.29_3
pkgname: dht-node repover: 0.1.0_1 srcpkgver: 0.1.0_3
pkgname: atom repover: 1.18.0_1 srcpkgver: 1.19.0_1
pkgname: ceph repover: 11.2.0_1 srcpkgver: 11.2.0_2
pkgname: swift repover: 2.2.1_2 srcpkgver: 2.2.1_3
pkgname: codelite repover: 11.0_1 srcpkgver: 11.0_2
pkgname: valabind repover: 0.10.0_2 srcpkgver: 1.4.0_1
pkgname: pdf2htmlEX repover: 0.14.6_12 srcpkgver: 0.14.6_13
```
